# This is a basic workflow to help you get started with Actions

# name: Deploy BOA to Oracle

# # Controls when the action will run.
# on:
#   # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ main ]

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#     - name: Deploy using ssh
#       uses: appleboy/ssh-action@v1.0.0
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USERNAME }}
#         key: ${{ secrets.PRIVATE_KEY }}
#         port: 22
#         script: |
#           /bin/bash
#           cd ~
#           source .profile
#           source .bashrc
#           cd ~/desarrollo/boa
#           git pull --rebase origin main
#           cargo build --release
#           sudo systemctl restart boa
#           exit
#           exit
